### ISSUE TITLE
The Programm stocks

### ISSUE THREAD

**Issue by yorklemb** [theace0296/BeatMapSynthesizer#2]
Hi There 
you give me an answer of my request withe only red cubes 
i dowload an try out your gui it looks realy profesionell.
but whith my Dell i7 Win 10 it do not work.
What do i worong ,
dowload and strart 
give the program the right directorys , and start the  Progress,
and booom nothing

best regards York

![1](https://user-images.githubusercontent.com/66382506/84041711-71f78900-a9a4-11ea-9194-916fbdb1a0a6.PNG)
![2](https://user-images.githubusercontent.com/66382506/84041716-7328b600-a9a4-11ea-879e-a35f22f89c62.PNG)
![3](https://user-images.githubusercontent.com/66382506/84041718-73c14c80-a9a4-11ea-990e-ff39c88d9a04.PNG)

**Comment by theace0296** [comment]
If you type CTRL+Shift+i, it should open the console log window, a successful run will look like the following:
![image](https://user-images.githubusercontent.com/29675446/84054460-6cd51280-a981-11ea-9229-2e07e0a346d2.png)

You will see "generateBeatMaps - Start" if the program has started running the script, depending on the size of the song, the process can take some time. Since the progress bar only updates when a song is finished, when doing one song it will stay at "0%" until the song is complete.

Let me know if you have any more issues!

**Comment by yorklemb** [comment]
Hi I Try
get This
![4](https://user-images.githubusercontent.com/66382506/84058335-619dd900-a9b9-11ea-84b1-8e6fa91198a6.PNG)

**Comment by theace0296** [comment]
Try deleting the following folder and trying again, I think I know what's going on
%appdata%\beat-map-synthesizer\temp

**Comment by yorklemb** [comment]
sorry maybe i am to stuipt 
i diden fond the file

![5](https://user-images.githubusercontent.com/66382506/84063971-294ec880-a9c2-11ea-8615-3737a2327007.PNG)
![6](https://user-images.githubusercontent.com/66382506/84063972-29e75f00-a9c2-11ea-96e4-1752aaddd274.PNG)

**Comment by theace0296** [comment]
Copy and paste the path `%appdata%\beat-map-synthesizer\` into Windows Explorer like so:

![image](https://user-images.githubusercontent.com/29675446/84066192-8bdca000-a993-11ea-929b-868d6cc7f2ea.png)

Then delete the "temp" folder:

![image](https://user-images.githubusercontent.com/29675446/84066284-af9fe600-a993-11ea-8fcd-a0eca0e9de6f.png)



You may also just need to wait longer for the map to be generated, it takes quite a bit of computational power.

**Comment by yorklemb** [comment]
No Same as before do you whant to have a look on my System over Skype or Anydesk, Teamviewer?
best regards York

**Comment by theace0296** [comment]
Could you attach the song you're trying to work on? It would let me see if there is something I haven't thought about causing it to freeze up.

**Comment by yorklemb** [comment]
hear is the Song
[Rhythm_Is_A_Dancer1245.zip](https://github.com/theace0296/BeatMapSynthesizer/files/4754924/Rhythm_Is_A_Dancer1245.zip)

**Comment by theace0296** [comment]
Try this hotfix release, turns out I wasn't properly handling songs that didn't have embedded cover art. 
https://github.com/theace0296/BeatMapSynthesizer/releases/tag/v0.4.1

Also here is the map I generated of that song, just in-case:
[Rhythm Is A Dancer (2008) (Genji Yoshida Remix) - Tom Novy, Snap.zip](https://github.com/theace0296/BeatMapSynthesizer/files/4755226/Rhythm.Is.A.Dancer.2008.Genji.Yoshida.Remix.-.Tom.Novy.Snap.zip)
